routes/admin.php
<?php

/* dashboard routes */
Route::get('/', function () {
    return redirect('/admin/pages');
});

/* dashboard */
Route::get('/dashboard', function () {
    return redirect('/admin/pages');
});
/* dashboard */

/* users */
Route::get('/users/draw',
    ['as' => 'admin.users.draw',
        'uses' => '\App\Http\Controllers\UserController@draw']
);

Route::resource('/users', 'UserController', [
    'as' => 'admin'
]);

Route::delete('/users/{id}/delete',
    ['as' => 'admin.users.delete',
        'uses' => '\App\Http\Controllers\UserController@destroy']
);
/* users */

/* roles */
Route::resource('/roles', 'RoleController', [
    'as' => 'admin'
]);

Route::delete('/roles/{id}/delete',
    ['as' => 'admin.roles.delete',
        'uses' => '\App\Http\Controllers\RoleController@destroy']
);
/* roles */

/* permissions */
Route::resource('/permissions', 'PermissionController', [
    'as' => 'admin'
]);

Route::delete('/permissions/{id}/delete',
    ['as' => 'admin.permissions.delete',
        'uses' => '\App\Http\Controllers\PermissionController@destroy']
);
/* permissions */

/* permission groups */
Route::resource('/permission_groups', 'PermissionGroupController', [
    'as' => 'admin'
]);

Route::delete('/permission_groups/{id}/delete',
    ['as' => 'admin.permission_groups.delete',
        'uses' => '\App\Http\Controllers\PermissionGroupController@destroy']
);
/* permission groups */

/* system settings */
Route::resource('/system_settings', 'SystemSettingController', [
    'as' => 'admin',
]);

Route::delete('/system_settings/{id}/delete',
    ['as' => 'admin.system_settings.delete',
        'uses' => '\App\Http\Controllers\SystemSettingController@destroy']
);
/* system settings */

/* posts */
Route::resource('/posts', 'PostController', [
    'as' => 'admin'
]);

Route::delete('/posts/{id}/delete',
    ['as' => 'admin.posts.delete',
        'uses' => '\App\Http\Controllers\PostController@destroy']
);
/* posts */

/* pages */
Route::resource('/pages', 'PageController', [
    'as' => 'admin'
]);

Route::delete('/pages/{id}/delete',
    ['as' => 'admin.pages.delete',
        'uses' => '\App\Http\Controllers\PageController@destroy']
);
/* pages */

/* ckeditor image upload */
Route::post('/ckeditor_image_upload',
    ['as' => 'admin.ckeditor_image_upload',
        'uses' => '\App\Http\Controllers\PageController@ckEditorImageUpload']
);
/* ckeditor image upload */

/* home_slides */
Route::resource('/home_slides', 'HomeSlideController', [
    'as' => 'admin'
]);

Route::delete('/home_slides/{id}/delete',
    ['as' => 'admin.home_slides.delete',
        'uses' => '\App\Http\Controllers\HomeSlideController@destroy']
);
/* home_slides */

/* contacts */
Route::resource('/contacts', 'ContactController', [
    'as' => 'admin'
]);

Route::delete('/contacts/{id}/delete',
    ['as' => 'admin.contacts.delete',
        'uses' => '\App\Http\Controllers\ContactController@destroy']
);
/* contacts */

/* faqs */
Route::resource('/faqs', 'FAQController', [
    'as' => 'admin'
]);

Route::delete('/faqs/{id}/delete',
    ['as' => 'admin.faqs.delete',
        'uses' => '\App\Http\Controllers\FAQController@destroy']
);
/* faqs */

/* galleries */
Route::resource('/galleries', 'GalleryController', [
    'as' => 'admin'
]);

Route::delete('/galleries/{id}/delete',
    ['as' => 'admin.galleries.delete',
        'uses' => '\App\Http\Controllers\GalleryController@destroy']
);
/* galleries */

/* shapes */
//Route::resource('/shapes', 'ShapeController', [
//    'as' => 'admin'
//]);

Route::get('/shapes',
    ['as' => 'admin.shapes.index',
        'uses' => 'ShapeController@index']
);
Route::get('/shapes/create/{parent_id?}',
    ['as' => 'admin.shapes.create',
        'uses' => 'ShapeController@create']
);
Route::post('/shapes/store/{parent_id?}',
    ['as' => 'admin.shapes.store',
        'uses' => 'ShapeController@store']
);
Route::get('/shapes/{id}/edit',
    ['as' => 'admin.shapes.edit',
        'uses' => 'ShapeController@edit']
);
Route::put('/shapes/{id}/update/{parent_id?}',
    ['as' => 'admin.shapes.update',
        'uses' => 'ShapeController@update']
);
Route::delete('/shapes/{id}/delete',
    ['as' => 'admin.shapes.delete',
        'uses' => '\App\Http\Controllers\ShapeController@destroy']
);
Route::get('/shapes/{parent_id?}',
    ['as' => 'admin.shapes.show',
        'uses' => 'ShapeController@show']
);
/* shapes */

/* sizes */
//Route::resource('/sizes', 'SizeController', [
//    'as' => 'admin'
//]);
//
//Route::delete('/sizes/{id}/delete',
//    ['as' => 'admin.sizes.delete',
//        'uses' => '\App\Http\Controllers\SizeController@destroy']
//);

Route::get('/sizes/{shape_id}',
    ['as' => 'admin.sizes.index',
        'uses' => 'SizeController@index']
);
Route::get('/sizes/create/{shape_id}',
    ['as' => 'admin.sizes.create',
        'uses' => 'SizeController@create']
);
Route::post('/sizes/store/{shape_id}',
    ['as' => 'admin.sizes.store',
        'uses' => 'SizeController@store']
);
Route::get('/sizes/{id}/edit',
    ['as' => 'admin.sizes.edit',
        'uses' => 'SizeController@edit']
);
Route::put('/sizes/{id}/update/{shape_id}',
    ['as' => 'admin.sizes.update',
        'uses' => 'SizeController@update']
);
Route::delete('/sizes/{id}/delete',
    ['as' => 'admin.sizes.delete',
        'uses' => '\App\Http\Controllers\SizeController@destroy']
);
/* sizes */

/* quantities */
//Route::resource('/quantities', 'QuantityController', [
//    'as' => 'admin'
//]);
//
//Route::delete('/quantities/{id}/delete',
//    ['as' => 'admin.quantities.delete',
//        'uses' => '\App\Http\Controllers\QuantityController@destroy']
//);

Route::get('/quantities/{size_id}',
    ['as' => 'admin.quantities.index',
        'uses' => 'QuantityController@index']
);
Route::get('/quantities/create/{size_id}',
    ['as' => 'admin.quantities.create',
        'uses' => 'QuantityController@create']
);
Route::post('/quantities/store/{size_id}',
    ['as' => 'admin.quantities.store',
        'uses' => 'QuantityController@store']
);
Route::get('/quantities/{id}/edit',
    ['as' => 'admin.quantities.edit',
        'uses' => 'QuantityController@edit']
);
Route::put('/quantities/{id}/update/{size_id}',
    ['as' => 'admin.quantities.update',
        'uses' => 'QuantityController@update']
);
Route::delete('/quantities/{id}/delete',
    ['as' => 'admin.quantities.delete',
        'uses' => '\App\Http\Controllers\QuantityController@destroy']
);
/* quantities */

/* designs */
//Route::resource('/designs', 'DesignController', [
//    'as' => 'admin'
//]);
//
//Route::delete('/designs/{id}/delete',
//    ['as' => 'admin.designs.delete',
//        'uses' => '\App\Http\Controllers\DesignController@destroy']
//);

Route::get('/designs/{shape_id}',
    ['as' => 'admin.designs.index',
        'uses' => 'DesignController@index']
);
Route::get('/designs/create/{shape_id}',
    ['as' => 'admin.designs.create',
        'uses' => 'DesignController@create']
);
Route::post('/designs/store/{shape_id}',
    ['as' => 'admin.designs.store',
        'uses' => 'DesignController@store']
);
Route::get('/designs/{id}/edit',
    ['as' => 'admin.designs.edit',
        'uses' => 'DesignController@edit']
);
Route::put('/designs/{id}/update/{shape_id}',
    ['as' => 'admin.designs.update',
        'uses' => 'DesignController@update']
);
Route::delete('/designs/{id}/delete',
    ['as' => 'admin.designs.delete',
        'uses' => '\App\Http\Controllers\DesignController@destroy']
);
/* designs */

/* materials */
Route::resource('/materials', 'MaterialController', [
    'as' => 'admin'
]);

Route::delete('/materials/{id}/delete',
    ['as' => 'admin.materials.delete',
        'uses' => '\App\Http\Controllers\MaterialController@destroy']
);
/* materials */

/* products */
Route::post('/products/upload_image', [
    'uses' => '\App\Http\Controllers\ProductController@uploadImage',
    'as' => 'admin.products.upload_image'
]);
Route::delete('/products/delete_image', [
    'uses' => '\App\Http\Controllers\ProductController@deleteImage',
    'as' => 'admin.products.delete_image'
]);

Route::resource('/products', 'ProductController', [
    'as' => 'admin'
]);

Route::delete('/products/{id}/delete',
    ['as' => 'admin.products.delete',
        'uses' => '\App\Http\Controllers\ProductController@destroy']
);
/* products */

/* coupon_codes */
Route::resource('/coupon_codes', 'CouponCodeController', [
    'as' => 'admin'
]);

Route::delete('/coupon_codes/{id}/delete',
    ['as' => 'admin.coupon_codes.delete',
        'uses' => '\App\Http\Controllers\CouponCodeController@destroy']
);
/* coupon_codes */

/* taxes */
Route::get('/taxes/draw',
    ['as' => 'admin.taxes.draw',
        'uses' => '\App\Http\Controllers\TaxController@draw']
);

Route::resource('/taxes', 'TaxController', [
    'as' => 'admin'
]);
/* taxes */

/* orders */
Route::get('/orders/draw', [
        'as' => 'admin.orders.draw',
        'uses' => '\App\Http\Controllers\OrderController@draw']
);

Route::post('/orders/{id}/update_status',
    ['as' => 'admin.orders.update_status',
        'uses' => '\App\Http\Controllers\OrderController@updateStatus']
);

Route::resource('/orders', 'OrderController', [
    'as' => 'admin'
]);

Route::delete('/orders/{id}/delete',
    ['as' => 'admin.orders.delete',
        'uses' => '\App\Http\Controllers\OrderController@destroy']
);
/* orders */

/* why_choose_us_sections */
Route::resource('/why_choose_us_sections', 'WhyChooseUsSectionController', [
    'as' => 'admin'
]);

Route::delete('/why_choose_us_sections/{id}/delete',
    ['as' => 'admin.why_choose_us_sections.delete',
        'uses' => '\App\Http\Controllers\WhyChooseUsSectionController@destroy']
);
/* why_choose_us_sections */

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

app/Models/Gallery.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Gallery
 * @package App\Models
 * @author Randall Anthony Bondoc
 */
class Gallery extends Model
{
    use SoftDeletes;

    protected $table = 'galleries';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'image',
        'description',
        'is_active',
    ];
}

app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Gallery;
use App\Repositories\GalleryRepository;

/**
 * Class GalleryController
 * @package App\Http\Controllers
 * @author Randall Anthony Bondoc
 */
class GalleryController extends Controller
{
    /**
     * Gallery model instance.
     *
     * @var Gallery
     */
    private $gallery_model;

    /**
     * GalleryRepository repository instance.
     *
     * @var GalleryRepository
     */
    private $gallery_repository;

    /**
     * Create a new controller instance.
     *
     * @param Gallery $gallery_model
     * @param GalleryRepository $gallery_repository
     */
    public function __construct(Gallery $gallery_model, GalleryRepository $gallery_repository)
    {
        /*
         * Model namespace
         * using $this->gallery_model can also access $this->gallery_model->where('id', 1)->get();
         * */
        $this->gallery_model = $gallery_model;

        /*
         * Repository namespace
         * this class may include methods that can be used by other controllers, like getting of galleries with other data (related tables).
         * */
        $this->gallery_repository = $gallery_repository;

//        $this->middleware(['isAdmin']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        if (!auth()->user()->hasPermissionTo('Read Gallery')) {
            abort('401', '401');
        }

        $galleries = $this->gallery_model->get();

        return view('admin.pages.gallery.index', compact('galleries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (!auth()->user()->hasPermissionTo('Create Gallery')) {
            abort('401', '401');
        }

        return view('admin.pages.gallery.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        if (!auth()->user()->hasPermissionTo('Create Gallery')) {
            abort('401', '401');
        }

        $this->validate($request, [
            'description' => 'required',
            'image' => 'required|mimes:jpg,jpeg,png',
        ]);

        $input = $request->all();
//        $input['is_active'] = isset($input['is_active']) ? 1 : 0;
        /* if slug is hidden, generate slug automatically */
//        $input['slug'] = str_slug($input['name']);

        $gallery = $this->gallery_model->create($input);

        if ($request->hasFile('image')) {
            $file_upload_path = $this->gallery_repository->uploadFile($request->file('image'), $gallery);
            $gallery->fill(['image' => $file_upload_path])->save();
        }

        return redirect()->route('admin.galleries.index')->with('flash_message', [
            'title' => '',
            'message' => 'Gallery ' . $gallery->title . ' successfully added.',
            'type' => 'success'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect()->route('admin.galleries.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (!auth()->user()->hasPermissionTo('Update Gallery')) {
            abort('401', '401');
        }

        $gallery = $this->gallery_model->findOrFail($id);

        return view('admin.pages.gallery.edit', compact('gallery'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, $id)
    {
        if (!auth()->user()->hasPermissionTo('Update Gallery')) {
            abort('401', '401');
        }

        $this->validate($request, [
            'description' => 'required',
            'image' => 'required_if:remove_image,==,1|mimes:jpg,jpeg,png',
        ], [
            'image.required_if' => 'The :attribute field is required if :attribute is removed.'
        ]);

        $gallery = $this->gallery_model->findOrFail($id);
        $input = $request->all();
//        $input['is_active'] = isset($input['is_active']) ? 1 : 0;
        /* if slug is hidden, generate slug automatically */
//        $input['slug'] = str_slug($input['name']);

        if ($request->hasFile('image')) {
            $file_upload_path = $this->gallery_repository->uploadFile($request->file('image'), $gallery);
            $input['image'] = $file_upload_path;
        }
        if ($request->has('remove_image') && $request->get('remove_image')) {
            $input['image'] = '';
        }

        $gallery->fill($input)->save();

        return redirect()->route('admin.galleries.index')->with('flash_message', [
            'title' => '',
            'message' => 'Gallery ' . $gallery->title . ' successfully updated.',
            'type' => 'success'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!auth()->user()->hasPermissionTo('Delete Gallery')) {
            abort('401', '401');
        }

        $gallery = $this->gallery_model->findOrFail($id);
        $gallery->delete();

        $response = array(
            'status' => FALSE,
            'data' => array(),
            'message' => array(),
        );

        $response['message'][] = 'Gallery successfully deleted.';
        $response['data']['id'] = $id;
        $response['status'] = TRUE;

        return response()->json($response);
    }
}

resources/views/admin/pages/gallery/create.blade.php
@extends('admin.layouts.base')

@section('content')
    <ul class="breadcrumb breadcrumb-top">
        <li><a href="{{ route('admin.galleries.index') }}">Galleries</a></li>
        <li><span href="javascript:void(0)">Add New Gallery</span></li>
    </ul>
    <div class="row">
        {{  Form::open([
            'method' => 'POST',
            'id' => 'create-gallery',
            'route' => ['admin.galleries.store'],
            'class' => 'form-horizontal ',
            'files' => TRUE
            ])
        }}
        <div class="col-md-12">
            <div class="block">
                <div class="block-title">
                    <h2><i class="fa fa-pencil"></i> <strong>Add new Gallery</strong></h2>
                </div>
                <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="gallery_image">Image</label>
                    <div class="col-md-9">
                        <div class="input-group">
                            <label class="input-group-btn">
                            <span class="btn btn-primary">
                                Choose File <input type="file" name="image" style="display: none;">
                            </span>
                            </label>
                            <input type="text" class="form-control" readonly>
                        </div>
                        @if($errors->has('image'))
                            <span class="help-block animation-slideDown">{{ $errors->first('image') }}</span>
                        @endif
                    </div>
                    <div class="col-md-offset-3 col-md-9">
                        <a href="" class="zoom img-thumbnail" style="cursor: default !important;" data-toggle="lightbox-image">
                            <img src="" alt="" class="img-responsive center-block" style="max-width: 100px;">
                        </a>
                        <br>
                        <a href="javascript:void(0)" class="btn btn-xs btn-danger remove-image-btn" style="display: none;"><i class="fa fa-trash"></i> Remove</a>
                        <input type="hidden" name="remove_image" class="remove-image" value="0">
                    </div>
                </div>
                <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="gallery_description">Description</label>

                    <div class="col-md-9">
                        <textarea id="gallery_description" name="description" rows="9"
                                  class="form-control " placeholder="Enter Gallery description..">{{ old('description') }}</textarea>
                        @if($errors->has('description'))
                            <span class="help-block animation-slideDown">{{ $errors->first('description') }}</span>
                        @endif
                    </div>
                </div>
                <div class="form-group form-actions">
                    <div class="col-md-9 col-md-offset-3">
                        <a href="{{ route('admin.galleries.index') }}" class="btn btn-sm btn-warning">Cancel</a>
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-floppy-o"></i> Save
                        </button>
                    </div>
                </div>
            </div>
        </div>
        {{ Form::close() }}
    </div>
@endsection

@push('extrascripts')
    <script type="text/javascript" src="{{ asset('public/js/ckeditor/ckeditor.js') }}"></script>
    <script type="text/javascript" src="{{ asset('public/js/libraries/galleries.js') }}"></script>
@endpush

resources/views/admin/pages/gallery/edit.blade.php
@extends('admin.layouts.base')

@section('content')
    <ul class="breadcrumb breadcrumb-top">
        <li><a href="{{ route('admin.galleries.index') }}">Galleries</a></li>
        <li><span href="javascript:void(0)">Edit Gallery</span></li>
    </ul>
    <div class="row">
        {{  Form::open([
            'method' => 'PUT',
            'id' => 'edit-gallery',
            'route' => ['admin.galleries.update', $gallery->id],
            'class' => 'form-horizontal ',
            'files' => TRUE
            ])
        }}
        <div class="col-md-12">
            <div class="block">
                <div class="block-title">
                    <h2><i class="fa fa-pencil"></i> <strong>Edit Gallery {{--"{{$gallery->name}}"--}}</strong></h2>
                </div>
                <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="image">Image</label>
                    <div class="col-md-9">
                        <div class="input-group">
                            <label class="input-group-btn">
                                <span class="btn btn-primary">
                                    Choose File <input type="file" name="image" style="display: none;">
                                </span>
                            </label>
                            <input type="text" class="form-control" readonly>
                        </div>
                        @if($errors->has('image'))
                            <span class="help-block animation-slideDown">{{ $errors->first('image') }}</span>
                        @endif
                    </div>
                    <div class="col-md-offset-3 col-md-9">
                        <a href="{{ asset($gallery->image) }}" class="zoom img-thumbnail" style="cursor: default !important;" data-toggle="lightbox-image">
                            <img src="{{ $gallery->image != '' ? asset($gallery->image) : '' }}"
                                 alt="{{ $gallery->image != '' ? asset($gallery->image) : '' }}"
                                 class="img-responsive center-block" style="max-width: 100px;">
                        </a>
                        <br>
                        <a href="javascript:void(0)" class="btn btn-xs btn-danger remove-image-btn"
                           style="display: {{ $gallery->image != '' ? '' : 'none' }};"><i class="fa fa-trash"></i> Remove</a>
                        <input type="hidden" name="remove_image" class="remove-image" value="0">
                    </div>
                </div>

                <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="gallery_description">Description</label>

                    <div class="col-md-9">
                    <textarea id="gallery_description" name="description" rows="9" class="form-control "
                              placeholder="Enter Gallery description..">{!! Request::old('description') ? : $gallery->description !!}</textarea>
                        @if($errors->has('description'))
                            <span class="help-block animation-slideDown">{{ $errors->first('description') }}</span>
                        @endif
                    </div>
                </div>
                <div class="form-group form-actions">
                    <div class="col-md-9 col-md-offset-3">
                        <a href="{{ route('admin.galleries.index') }}" class="btn btn-sm btn-warning">Cancel</a>
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-floppy-o"></i> Save
                        </button>
                    </div>
                </div>
            </div>
        </div>
        {{ Form::close() }}
    </div>
@endsection

@push('extrascripts')
    <script type="text/javascript" src="{{ asset('public/js/ckeditor/ckeditor.js') }}"></script>
    <script type="text/javascript" src="{{ asset('public/js/libraries/galleries.js') }}"></script>
@endpush

resources/views/admin/pages/gallery/index.blade.php
@extends('admin.layouts.base')

@section('content')
    @if (auth()->user()->can('Create Gallery'))
        <div class="row text-center">
            <div class="col-sm-12 col-lg-12">
                <a href="{{ route('admin.galleries.create') }}" class="widget widget-hover-effect2">
                    <div class="widget-extra themed-background">
                        <h4 class="widget-content-light">
                            <strong>Add New</strong>
                            Gallery
                        </h4>
                    </div>
                    <div class="widget-extra-full">
                        <span class="h2 text-primary animation-expandOpen">
                            <i class="fa fa-plus"></i>
                        </span>
                    </div>
                </a>
            </div>
        </div>
    @endif
    <div class="block full">
        <div class="block-title">
            <h2>
                <i class="fa fa-file-image-o sidebar-nav-icon"></i>
                <strong>Galleries</strong>
            </h2>
        </div>
        <div class="alert alert-info alert-dismissable gallery-empty {{$galleries->count() == 0 ? '' : 'johnCena' }}">
            <i class="fa fa-info-circle"></i> No Galleries found.
        </div>
        <div class="table-responsive {{$galleries->count() == 0 ? 'johnCena' : '' }}">
            <table id="galleries-table" class="table table-bordered table-striped table-vcenter">
                <thead>
                <tr role="row">
                    <th class="text-center">
                        ID
                    </th>
                    <th class="text-center">
                        Image
                    </th>
                    <th class="text-left">
                        Description
                    </th>
                    <th class="text-center">
                        Date Created
                    </th>
                    <th class="text-center">
                        Action
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach($galleries as $gallery)
                    <tr data-gallery-id="{{$gallery->id}}">
                        <td class="text-center"><strong>{{ $gallery->id }}</strong></td>
                        <td class="text-center"><img class="img img-thumbnail" width="100px" src="{{ asset($gallery->image) }}"></td>
                        <td class="text-left">{!! str_limit(strip_tags($gallery->description), 50) !!}</td>
                        <td class="text-center">{{ $gallery->created_at->format('F d, Y') }}</td>
                        <td class="text-center">
                            <div class="btn-group btn-group-xs">
                                @if (auth()->user()->can('Update Gallery'))
                                    <a href="{{ route('admin.galleries.edit', $gallery->id) }}"
                                       data-toggle="tooltip"
                                       title=""
                                       class="btn btn-default"
                                       data-original-title="Edit"><i class="fa fa-pencil"></i></a>
                                @endif
                                @if (auth()->user()->can('Delete Gallery'))
                                    <a href="javascript:void(0)" data-toggle="tooltip"
                                       title=""
                                       class="btn btn-xs btn-danger delete-gallery-btn"
                                       data-original-title="Delete"
                                       data-gallery-id="{{ $gallery->id }}"
                                       data-gallery-route="{{ route('admin.galleries.delete', $gallery->id) }}">
                                        <i class="fa fa-times"></i>
                                    </a>
                                @endif
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

@push('extrascripts')
    <script type="text/javascript" src="{{ asset('public/js/libraries/galleries.js') }}"></script>
@endpush