routes/admin.php
<?php

/* dashboard routes */
Route::get('/', function () {
    return redirect('/admin/pages');
});

/* dashboard */
Route::get('/dashboard', function () {
    return redirect('/admin/pages');
});
/* dashboard */

/* users */
Route::get('/users/draw',
    ['as' => 'admin.users.draw',
        'uses' => '\App\Http\Controllers\UserController@draw']
);

Route::resource('/users', 'UserController', [
    'as' => 'admin'
]);

Route::delete('/users/{id}/delete',
    ['as' => 'admin.users.delete',
        'uses' => '\App\Http\Controllers\UserController@destroy']
);
/* users */

/* roles */
Route::resource('/roles', 'RoleController', [
    'as' => 'admin'
]);

Route::delete('/roles/{id}/delete',
    ['as' => 'admin.roles.delete',
        'uses' => '\App\Http\Controllers\RoleController@destroy']
);
/* roles */

/* permissions */
Route::resource('/permissions', 'PermissionController', [
    'as' => 'admin'
]);

Route::delete('/permissions/{id}/delete',
    ['as' => 'admin.permissions.delete',
        'uses' => '\App\Http\Controllers\PermissionController@destroy']
);
/* permissions */

/* permission groups */
Route::resource('/permission_groups', 'PermissionGroupController', [
    'as' => 'admin'
]);

Route::delete('/permission_groups/{id}/delete',
    ['as' => 'admin.permission_groups.delete',
        'uses' => '\App\Http\Controllers\PermissionGroupController@destroy']
);
/* permission groups */

/* system settings */
Route::resource('/system_settings', 'SystemSettingController', [
    'as' => 'admin',
]);

Route::delete('/system_settings/{id}/delete',
    ['as' => 'admin.system_settings.delete',
        'uses' => '\App\Http\Controllers\SystemSettingController@destroy']
);
/* system settings */

/* posts */
Route::resource('/posts', 'PostController', [
    'as' => 'admin'
]);

Route::delete('/posts/{id}/delete',
    ['as' => 'admin.posts.delete',
        'uses' => '\App\Http\Controllers\PostController@destroy']
);
/* posts */

/* pages */
Route::resource('/pages', 'PageController', [
    'as' => 'admin'
]);

Route::delete('/pages/{id}/delete',
    ['as' => 'admin.pages.delete',
        'uses' => '\App\Http\Controllers\PageController@destroy']
);
/* pages */

/* ckeditor image upload */
Route::post('/ckeditor_image_upload',
    ['as' => 'admin.ckeditor_image_upload',
        'uses' => '\App\Http\Controllers\PageController@ckEditorImageUpload']
);
/* ckeditor image upload */

/* home_slides */
Route::resource('/home_slides', 'HomeSlideController', [
    'as' => 'admin'
]);

Route::delete('/home_slides/{id}/delete',
    ['as' => 'admin.home_slides.delete',
        'uses' => '\App\Http\Controllers\HomeSlideController@destroy']
);
/* home_slides */

/* contacts */
Route::resource('/contacts', 'ContactController', [
    'as' => 'admin'
]);

Route::delete('/contacts/{id}/delete',
    ['as' => 'admin.contacts.delete',
        'uses' => '\App\Http\Controllers\ContactController@destroy']
);
/* contacts */

/* faqs */
Route::resource('/faqs', 'FAQController', [
    'as' => 'admin'
]);

Route::delete('/faqs/{id}/delete',
    ['as' => 'admin.faqs.delete',
        'uses' => '\App\Http\Controllers\FAQController@destroy']
);
/* faqs */

/* galleries */
Route::resource('/galleries', 'GalleryController', [
    'as' => 'admin'
]);

Route::delete('/galleries/{id}/delete',
    ['as' => 'admin.galleries.delete',
        'uses' => '\App\Http\Controllers\GalleryController@destroy']
);
/* galleries */

/* shapes */
//Route::resource('/shapes', 'ShapeController', [
//    'as' => 'admin'
//]);

Route::get('/shapes',
    ['as' => 'admin.shapes.index',
        'uses' => 'ShapeController@index']
);
Route::get('/shapes/create/{parent_id?}',
    ['as' => 'admin.shapes.create',
        'uses' => 'ShapeController@create']
);
Route::post('/shapes/store/{parent_id?}',
    ['as' => 'admin.shapes.store',
        'uses' => 'ShapeController@store']
);
Route::get('/shapes/{id}/edit',
    ['as' => 'admin.shapes.edit',
        'uses' => 'ShapeController@edit']
);
Route::put('/shapes/{id}/update/{parent_id?}',
    ['as' => 'admin.shapes.update',
        'uses' => 'ShapeController@update']
);
Route::delete('/shapes/{id}/delete',
    ['as' => 'admin.shapes.delete',
        'uses' => '\App\Http\Controllers\ShapeController@destroy']
);
Route::get('/shapes/{parent_id?}',
    ['as' => 'admin.shapes.show',
        'uses' => 'ShapeController@show']
);
/* shapes */

/* sizes */
//Route::resource('/sizes', 'SizeController', [
//    'as' => 'admin'
//]);
//
//Route::delete('/sizes/{id}/delete',
//    ['as' => 'admin.sizes.delete',
//        'uses' => '\App\Http\Controllers\SizeController@destroy']
//);

Route::get('/sizes/{shape_id}',
    ['as' => 'admin.sizes.index',
        'uses' => 'SizeController@index']
);
Route::get('/sizes/create/{shape_id}',
    ['as' => 'admin.sizes.create',
        'uses' => 'SizeController@create']
);
Route::post('/sizes/store/{shape_id}',
    ['as' => 'admin.sizes.store',
        'uses' => 'SizeController@store']
);
Route::get('/sizes/{id}/edit',
    ['as' => 'admin.sizes.edit',
        'uses' => 'SizeController@edit']
);
Route::put('/sizes/{id}/update/{shape_id}',
    ['as' => 'admin.sizes.update',
        'uses' => 'SizeController@update']
);
Route::delete('/sizes/{id}/delete',
    ['as' => 'admin.sizes.delete',
        'uses' => '\App\Http\Controllers\SizeController@destroy']
);
/* sizes */

/* quantities */
//Route::resource('/quantities', 'QuantityController', [
//    'as' => 'admin'
//]);
//
//Route::delete('/quantities/{id}/delete',
//    ['as' => 'admin.quantities.delete',
//        'uses' => '\App\Http\Controllers\QuantityController@destroy']
//);

Route::get('/quantities/{size_id}',
    ['as' => 'admin.quantities.index',
        'uses' => 'QuantityController@index']
);
Route::get('/quantities/create/{size_id}',
    ['as' => 'admin.quantities.create',
        'uses' => 'QuantityController@create']
);
Route::post('/quantities/store/{size_id}',
    ['as' => 'admin.quantities.store',
        'uses' => 'QuantityController@store']
);
Route::get('/quantities/{id}/edit',
    ['as' => 'admin.quantities.edit',
        'uses' => 'QuantityController@edit']
);
Route::put('/quantities/{id}/update/{size_id}',
    ['as' => 'admin.quantities.update',
        'uses' => 'QuantityController@update']
);
Route::delete('/quantities/{id}/delete',
    ['as' => 'admin.quantities.delete',
        'uses' => '\App\Http\Controllers\QuantityController@destroy']
);
/* quantities */

/* designs */
//Route::resource('/designs', 'DesignController', [
//    'as' => 'admin'
//]);
//
//Route::delete('/designs/{id}/delete',
//    ['as' => 'admin.designs.delete',
//        'uses' => '\App\Http\Controllers\DesignController@destroy']
//);

Route::get('/designs/{shape_id}',
    ['as' => 'admin.designs.index',
        'uses' => 'DesignController@index']
);
Route::get('/designs/create/{shape_id}',
    ['as' => 'admin.designs.create',
        'uses' => 'DesignController@create']
);
Route::post('/designs/store/{shape_id}',
    ['as' => 'admin.designs.store',
        'uses' => 'DesignController@store']
);
Route::get('/designs/{id}/edit',
    ['as' => 'admin.designs.edit',
        'uses' => 'DesignController@edit']
);
Route::put('/designs/{id}/update/{shape_id}',
    ['as' => 'admin.designs.update',
        'uses' => 'DesignController@update']
);
Route::delete('/designs/{id}/delete',
    ['as' => 'admin.designs.delete',
        'uses' => '\App\Http\Controllers\DesignController@destroy']
);
/* designs */

/* materials */
Route::resource('/materials', 'MaterialController', [
    'as' => 'admin'
]);

Route::delete('/materials/{id}/delete',
    ['as' => 'admin.materials.delete',
        'uses' => '\App\Http\Controllers\MaterialController@destroy']
);
/* materials */

/* products */
Route::post('/products/upload_image', [
    'uses' => '\App\Http\Controllers\ProductController@uploadImage',
    'as' => 'admin.products.upload_image'
]);
Route::delete('/products/delete_image', [
    'uses' => '\App\Http\Controllers\ProductController@deleteImage',
    'as' => 'admin.products.delete_image'
]);

Route::resource('/products', 'ProductController', [
    'as' => 'admin'
]);

Route::delete('/products/{id}/delete',
    ['as' => 'admin.products.delete',
        'uses' => '\App\Http\Controllers\ProductController@destroy']
);
/* products */

/* coupon_codes */
Route::resource('/coupon_codes', 'CouponCodeController', [
    'as' => 'admin'
]);

Route::delete('/coupon_codes/{id}/delete',
    ['as' => 'admin.coupon_codes.delete',
        'uses' => '\App\Http\Controllers\CouponCodeController@destroy']
);
/* coupon_codes */

/* taxes */
Route::get('/taxes/draw',
    ['as' => 'admin.taxes.draw',
        'uses' => '\App\Http\Controllers\TaxController@draw']
);

Route::resource('/taxes', 'TaxController', [
    'as' => 'admin'
]);
/* taxes */

/* orders */
Route::get('/orders/draw', [
        'as' => 'admin.orders.draw',
        'uses' => '\App\Http\Controllers\OrderController@draw']
);

Route::post('/orders/{id}/update_status',
    ['as' => 'admin.orders.update_status',
        'uses' => '\App\Http\Controllers\OrderController@updateStatus']
);

Route::resource('/orders', 'OrderController', [
    'as' => 'admin'
]);

Route::delete('/orders/{id}/delete',
    ['as' => 'admin.orders.delete',
        'uses' => '\App\Http\Controllers\OrderController@destroy']
);
/* orders */

/* why_choose_us_sections */
Route::resource('/why_choose_us_sections', 'WhyChooseUsSectionController', [
    'as' => 'admin'
]);

Route::delete('/why_choose_us_sections/{id}/delete',
    ['as' => 'admin.why_choose_us_sections.delete',
        'uses' => '\App\Http\Controllers\WhyChooseUsSectionController@destroy']
);
/* why_choose_us_sections */

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

resources/views/admin/pages/tax/edit.blade.php
@extends('admin.layouts.base')

@section('content')
    <ul class="breadcrumb breadcrumb-top">
        <li><a href="{{ route('admin.taxes.index') }}">Taxes</a></li>
        <li><span href="javascript:void(0)">Edit Tax</span></li>
    </ul>
    <div class="row">
        {{  Form::open([
            'method' => 'PUT',
            'id' => 'edit-tax',
            'route' => ['admin.taxes.update', $state->id],
            'class' => 'form-horizontal ',
            'files' => TRUE
            ])
        }}
        <div class="col-md-12">
            <div class="block">
                <div class="block-title">
                    <h2><i class="fa fa-pencil"></i> <strong>Edit Tax "{{$state->name}}"</strong></h2>
                </div>
                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="tax_name">Name</label>

                    <div class="col-md-9">
                        <input type="text" class="form-control" id="tax_name" name="name"
                               value="{{  Request::old('name') ? : $state->name }}"
                               placeholder="Enter name.." readonly>
                        @if($errors->has('name'))
                            <span class="help-block animation-slideDown">{{ $errors->first('name') }}</span>
                        @endif
                    </div>
                </div>
                <div class="form-group{{ $errors->has('tax') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="tax_tax">Tax</label>

                    <div class="col-md-9">
                        <input type="text" class="form-control input-number" id="tax_tax" name="tax"
                               value="{{  Request::old('tax') ? : $state->tax }}"
                               placeholder="0.0000">
                        @if($errors->has('tax'))
                            <span class="help-block animation-slideDown">{{ $errors->first('tax') }}</span>
                        @endif
                    </div>
                </div>
                <div class="form-group form-actions">
                    <div class="col-md-9 col-md-offset-3">
                        <a href="{{ route('admin.taxes.index') }}" class="btn btn-sm btn-warning">Cancel</a>
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-floppy-o"></i> Save
                        </button>
                    </div>
                </div>
            </div>
        </div>
        {{ Form::close() }}
    </div>
@endsection

@push('extrascripts')
    <script type="text/javascript" src="{{ asset('public/js/ckeditor/ckeditor.js') }}"></script>
    <script type="text/javascript" src="{{ asset('public/js/libraries/taxes.js') }}"></script>
@endpush

resources/views/admin/pages/tax/index.blade.php
@extends('admin.layouts.base')

@section('content')
    <div class="block full">
        <div class="block-title">
            <h2>
                <i class="fa fa-percent sidebar-nav-icon"></i>
                <strong>Taxes</strong>
            </h2>
        </div>
        <div class="alert alert-info alert-dismissable tax-empty {{$states->count() == 0 ? '' : 'johnCena' }}">
            <i class="fa fa-info-circle"></i> No States found.
        </div>
        <div class="table-responsive {{$states->count() == 0 ? 'johnCena' : '' }}">
            <table id="taxes-table" class="table table-bordered table-striped table-vcenter">
                <thead>
                <tr role="row">
                    <th class="text-left">
                        State
                    </th>
                    <th class="text-left">
                        Country
                    </th>
                    <th class="text-left">
                        Tax
                    </th>
                    <th class="text-center">
                        Action
                    </th>
                </tr>
                </thead>
                <tbody>
                {{--@foreach($states as $state)--}}
                    {{--<tr data-tax-id="{{$state->id}}">--}}
                        {{--<td class="text-left">{{ $state->name }}</td>--}}
                        {{--<td class="text-left">{{ !empty($state->country) ? $state->country->name : '' }}</td>--}}
                        {{--<td class="text-left">{{ $state->tax }}</td>--}}
                        {{--<td class="text-center">--}}
                            {{--<div class="btn-group btn-group-xs">--}}
                                {{--@if (auth()->user()->can('Update Tax'))--}}
                                    {{--<a href="{{ route('admin.taxes.edit', $state->id) }}"--}}
                                       {{--data-toggle="tooltip"--}}
                                       {{--title=""--}}
                                       {{--class="btn btn-default"--}}
                                       {{--data-original-title="Edit"><i class="fa fa-pencil"></i></a>--}}
                                {{--@endif--}}
                            {{--</div>--}}
                        {{--</td>--}}
                    {{--</tr>--}}
                {{--@endforeach--}}
                </tbody>
            </table>
        </div>
    </div>
@endsection

@push('extrascripts')
<script>
    var oCountries = {!! $countries !!}
</script>
    <script type="text/javascript" src="{{ asset('public/js/libraries/taxes.js') }}"></script>
@endpush