routes/admin.php
<?php

/* dashboard routes */
Route::get('/', function () {
    return redirect('/admin/pages');
});

/* dashboard */
Route::get('/dashboard', function () {
    return redirect('/admin/pages');
});
/* dashboard */

/* users */
Route::get('/users/draw',
    ['as' => 'admin.users.draw',
        'uses' => '\App\Http\Controllers\UserController@draw']
);

Route::resource('/users', 'UserController', [
    'as' => 'admin'
]);

Route::delete('/users/{id}/delete',
    ['as' => 'admin.users.delete',
        'uses' => '\App\Http\Controllers\UserController@destroy']
);
/* users */

/* roles */
Route::resource('/roles', 'RoleController', [
    'as' => 'admin'
]);

Route::delete('/roles/{id}/delete',
    ['as' => 'admin.roles.delete',
        'uses' => '\App\Http\Controllers\RoleController@destroy']
);
/* roles */

/* permissions */
Route::resource('/permissions', 'PermissionController', [
    'as' => 'admin'
]);

Route::delete('/permissions/{id}/delete',
    ['as' => 'admin.permissions.delete',
        'uses' => '\App\Http\Controllers\PermissionController@destroy']
);
/* permissions */

/* permission groups */
Route::resource('/permission_groups', 'PermissionGroupController', [
    'as' => 'admin'
]);

Route::delete('/permission_groups/{id}/delete',
    ['as' => 'admin.permission_groups.delete',
        'uses' => '\App\Http\Controllers\PermissionGroupController@destroy']
);
/* permission groups */

/* system settings */
Route::resource('/system_settings', 'SystemSettingController', [
    'as' => 'admin',
]);

Route::delete('/system_settings/{id}/delete',
    ['as' => 'admin.system_settings.delete',
        'uses' => '\App\Http\Controllers\SystemSettingController@destroy']
);
/* system settings */

/* posts */
Route::resource('/posts', 'PostController', [
    'as' => 'admin'
]);

Route::delete('/posts/{id}/delete',
    ['as' => 'admin.posts.delete',
        'uses' => '\App\Http\Controllers\PostController@destroy']
);
/* posts */

/* pages */
Route::resource('/pages', 'PageController', [
    'as' => 'admin'
]);

Route::delete('/pages/{id}/delete',
    ['as' => 'admin.pages.delete',
        'uses' => '\App\Http\Controllers\PageController@destroy']
);
/* pages */

/* ckeditor image upload */
Route::post('/ckeditor_image_upload',
    ['as' => 'admin.ckeditor_image_upload',
        'uses' => '\App\Http\Controllers\PageController@ckEditorImageUpload']
);
/* ckeditor image upload */

/* home_slides */
Route::resource('/home_slides', 'HomeSlideController', [
    'as' => 'admin'
]);

Route::delete('/home_slides/{id}/delete',
    ['as' => 'admin.home_slides.delete',
        'uses' => '\App\Http\Controllers\HomeSlideController@destroy']
);
/* home_slides */

/* contacts */
Route::resource('/contacts', 'ContactController', [
    'as' => 'admin'
]);

Route::delete('/contacts/{id}/delete',
    ['as' => 'admin.contacts.delete',
        'uses' => '\App\Http\Controllers\ContactController@destroy']
);
/* contacts */

/* faqs */
Route::resource('/faqs', 'FAQController', [
    'as' => 'admin'
]);

Route::delete('/faqs/{id}/delete',
    ['as' => 'admin.faqs.delete',
        'uses' => '\App\Http\Controllers\FAQController@destroy']
);
/* faqs */

/* galleries */
Route::resource('/galleries', 'GalleryController', [
    'as' => 'admin'
]);

Route::delete('/galleries/{id}/delete',
    ['as' => 'admin.galleries.delete',
        'uses' => '\App\Http\Controllers\GalleryController@destroy']
);
/* galleries */

/* shapes */
//Route::resource('/shapes', 'ShapeController', [
//    'as' => 'admin'
//]);

Route::get('/shapes',
    ['as' => 'admin.shapes.index',
        'uses' => 'ShapeController@index']
);
Route::get('/shapes/create/{parent_id?}',
    ['as' => 'admin.shapes.create',
        'uses' => 'ShapeController@create']
);
Route::post('/shapes/store/{parent_id?}',
    ['as' => 'admin.shapes.store',
        'uses' => 'ShapeController@store']
);
Route::get('/shapes/{id}/edit',
    ['as' => 'admin.shapes.edit',
        'uses' => 'ShapeController@edit']
);
Route::put('/shapes/{id}/update/{parent_id?}',
    ['as' => 'admin.shapes.update',
        'uses' => 'ShapeController@update']
);
Route::delete('/shapes/{id}/delete',
    ['as' => 'admin.shapes.delete',
        'uses' => '\App\Http\Controllers\ShapeController@destroy']
);
Route::get('/shapes/{parent_id?}',
    ['as' => 'admin.shapes.show',
        'uses' => 'ShapeController@show']
);
/* shapes */

/* sizes */
//Route::resource('/sizes', 'SizeController', [
//    'as' => 'admin'
//]);
//
//Route::delete('/sizes/{id}/delete',
//    ['as' => 'admin.sizes.delete',
//        'uses' => '\App\Http\Controllers\SizeController@destroy']
//);

Route::get('/sizes/{shape_id}',
    ['as' => 'admin.sizes.index',
        'uses' => 'SizeController@index']
);
Route::get('/sizes/create/{shape_id}',
    ['as' => 'admin.sizes.create',
        'uses' => 'SizeController@create']
);
Route::post('/sizes/store/{shape_id}',
    ['as' => 'admin.sizes.store',
        'uses' => 'SizeController@store']
);
Route::get('/sizes/{id}/edit',
    ['as' => 'admin.sizes.edit',
        'uses' => 'SizeController@edit']
);
Route::put('/sizes/{id}/update/{shape_id}',
    ['as' => 'admin.sizes.update',
        'uses' => 'SizeController@update']
);
Route::delete('/sizes/{id}/delete',
    ['as' => 'admin.sizes.delete',
        'uses' => '\App\Http\Controllers\SizeController@destroy']
);
/* sizes */

/* quantities */
//Route::resource('/quantities', 'QuantityController', [
//    'as' => 'admin'
//]);
//
//Route::delete('/quantities/{id}/delete',
//    ['as' => 'admin.quantities.delete',
//        'uses' => '\App\Http\Controllers\QuantityController@destroy']
//);

Route::get('/quantities/{size_id}',
    ['as' => 'admin.quantities.index',
        'uses' => 'QuantityController@index']
);
Route::get('/quantities/create/{size_id}',
    ['as' => 'admin.quantities.create',
        'uses' => 'QuantityController@create']
);
Route::post('/quantities/store/{size_id}',
    ['as' => 'admin.quantities.store',
        'uses' => 'QuantityController@store']
);
Route::get('/quantities/{id}/edit',
    ['as' => 'admin.quantities.edit',
        'uses' => 'QuantityController@edit']
);
Route::put('/quantities/{id}/update/{size_id}',
    ['as' => 'admin.quantities.update',
        'uses' => 'QuantityController@update']
);
Route::delete('/quantities/{id}/delete',
    ['as' => 'admin.quantities.delete',
        'uses' => '\App\Http\Controllers\QuantityController@destroy']
);
/* quantities */

/* designs */
//Route::resource('/designs', 'DesignController', [
//    'as' => 'admin'
//]);
//
//Route::delete('/designs/{id}/delete',
//    ['as' => 'admin.designs.delete',
//        'uses' => '\App\Http\Controllers\DesignController@destroy']
//);

Route::get('/designs/{shape_id}',
    ['as' => 'admin.designs.index',
        'uses' => 'DesignController@index']
);
Route::get('/designs/create/{shape_id}',
    ['as' => 'admin.designs.create',
        'uses' => 'DesignController@create']
);
Route::post('/designs/store/{shape_id}',
    ['as' => 'admin.designs.store',
        'uses' => 'DesignController@store']
);
Route::get('/designs/{id}/edit',
    ['as' => 'admin.designs.edit',
        'uses' => 'DesignController@edit']
);
Route::put('/designs/{id}/update/{shape_id}',
    ['as' => 'admin.designs.update',
        'uses' => 'DesignController@update']
);
Route::delete('/designs/{id}/delete',
    ['as' => 'admin.designs.delete',
        'uses' => '\App\Http\Controllers\DesignController@destroy']
);
/* designs */

/* materials */
Route::resource('/materials', 'MaterialController', [
    'as' => 'admin'
]);

Route::delete('/materials/{id}/delete',
    ['as' => 'admin.materials.delete',
        'uses' => '\App\Http\Controllers\MaterialController@destroy']
);
/* materials */

/* products */
Route::post('/products/upload_image', [
    'uses' => '\App\Http\Controllers\ProductController@uploadImage',
    'as' => 'admin.products.upload_image'
]);
Route::delete('/products/delete_image', [
    'uses' => '\App\Http\Controllers\ProductController@deleteImage',
    'as' => 'admin.products.delete_image'
]);

Route::resource('/products', 'ProductController', [
    'as' => 'admin'
]);

Route::delete('/products/{id}/delete',
    ['as' => 'admin.products.delete',
        'uses' => '\App\Http\Controllers\ProductController@destroy']
);
/* products */

/* coupon_codes */
Route::resource('/coupon_codes', 'CouponCodeController', [
    'as' => 'admin'
]);

Route::delete('/coupon_codes/{id}/delete',
    ['as' => 'admin.coupon_codes.delete',
        'uses' => '\App\Http\Controllers\CouponCodeController@destroy']
);
/* coupon_codes */

/* taxes */
Route::get('/taxes/draw',
    ['as' => 'admin.taxes.draw',
        'uses' => '\App\Http\Controllers\TaxController@draw']
);

Route::resource('/taxes', 'TaxController', [
    'as' => 'admin'
]);
/* taxes */

/* orders */
Route::get('/orders/draw', [
        'as' => 'admin.orders.draw',
        'uses' => '\App\Http\Controllers\OrderController@draw']
);

Route::post('/orders/{id}/update_status',
    ['as' => 'admin.orders.update_status',
        'uses' => '\App\Http\Controllers\OrderController@updateStatus']
);

Route::resource('/orders', 'OrderController', [
    'as' => 'admin'
]);

Route::delete('/orders/{id}/delete',
    ['as' => 'admin.orders.delete',
        'uses' => '\App\Http\Controllers\OrderController@destroy']
);
/* orders */

/* why_choose_us_sections */
Route::resource('/why_choose_us_sections', 'WhyChooseUsSectionController', [
    'as' => 'admin'
]);

Route::delete('/why_choose_us_sections/{id}/delete',
    ['as' => 'admin.why_choose_us_sections.delete',
        'uses' => '\App\Http\Controllers\WhyChooseUsSectionController@destroy']
);
/* why_choose_us_sections */

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

resources/views/admin/pages/page/create.blade.php
@extends('admin.layouts.base')

@section('content')
    <ul class="breadcrumb breadcrumb-top">
        <li><a href="{{ route('admin.pages.index') }}">Pages</a></li>
        <li><span href="javascript:void(0)">Add New Page</span></li>
    </ul>
    <div class="row">
        {{  Form::open([
            'method' => 'POST',
            'id' => 'create-page',
            'route' => ['admin.pages.store'],
            'class' => 'form-horizontal ',
            'files' => TRUE,
            ])
        }}
        <div class="col-md-12">
            <div class="block">
                <div class="block-title">
                    <h2><i class="fa fa-pencil"></i> <strong>Add new Page</strong></h2>
                </div>
                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="pages_name">Name</label>

                    <div class="col-md-9">
                        <input type="text" class="form-control" id="pages_name" name="name"
                               placeholder="Enter page name.." value="{{ old('name') }}">
                        @if($errors->has('name'))
                            <span class="help-block animation-slideDown">{{ $errors->first('name') }}</span>
                        @endif
                    </div>
                </div>
                <div class="form-group{{ $errors->has('slug') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="pages_slug">Slug</label>

                    <div class="col-md-9">
                        <input type="text" class="form-control" id="pages_slug" name="slug"
                               placeholder="Enter page slug.." value="{{ old('slug') }}">
                        @if($errors->has('slug'))
                            <span class="help-block animation-slideDown">{{ $errors->first('slug') }}</span>
                        @endif
                    </div>
                </div>
                {{--<div class="form-group{{ $errors->has('page_type') ? ' has-error' : '' }}">--}}
                    {{--<label class="col-md-3 control-label" for="page_type_id">Type</label>--}}

                    {{--<div class="col-md-9">--}}
                        {{--<select name="page_type_id" id="page_type_id"--}}
                                {{--class="page-type-select"--}}
                                {{--data-placeholder="Choose page type..">--}}
                            {{--<option value=""></option>--}}
                            {{--@foreach($page_types as $page_type)--}}
                                {{--<option value="{{ $page_type->id }}" {{ old('page_type_id') ? old('page_type_id') == $page_type->id ? 'selected' : '' : '' }}>{{ $page_type->name }}</option>--}}
                            {{--@endforeach--}}
                        {{--</select>--}}
                        {{--@if($errors->has('page_type'))--}}
                            {{--<span class="help-block animation-slideDown">{{ $errors->first('page_type') }}</span>--}}
                        {{--@endif--}}
                    {{--</div>--}}
                {{--</div>--}}

                {{--<div class="form-group{{ $errors->has('banner_image') ? ' has-error' : '' }}">--}}
                    {{--<label class="col-md-3 control-label" for="banner_image">Banner Image</label>--}}
                    {{--<div class="col-md-9">--}}
                        {{--<div class="input-group">--}}
                            {{--<label class="input-group-btn">--}}
                            {{--<span class="btn btn-primary">--}}
                                {{--Choose File <input type="file" name="banner_image" style="display: none;">--}}
                            {{--</span>--}}
                            {{--</label>--}}
                            {{--<input type="text" class="form-control" readonly>--}}
                        {{--</div>--}}
                        {{--@if($errors->has('banner_image'))--}}
                            {{--<span class="help-block animation-slideDown">{{ $errors->first('banner_image') }}</span>--}}
                        {{--@endif--}}
                    {{--</div>--}}
                {{--</div>--}}

                {{--<div class="form-group{{ $errors->has('banner_description') ? ' has-error' : '' }}">--}}
                    {{--<label class="col-md-3 control-label" for="banner_description">Banner Description</label>--}}

                    {{--<div class="col-md-9">--}}
                        {{--<textarea id="banner_description" name="banner_description" rows="9"--}}
                                  {{--class="form-control ckeditor"--}}
                                  {{--placeholder="Enter page banner description..">{{ old('banner_description') }}</textarea>--}}
                        {{--@if($errors->has('banner_description'))--}}
                            {{--<span class="help-block animation-slideDown">{{ $errors->first('banner_description') }}</span>--}}
                        {{--@endif--}}
                    {{--</div>--}}
                {{--</div>--}}
                <div class="form-group{{ $errors->has('content') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="page_content">Content</label>

                    <div class="col-md-9">
                            <textarea id="page_content" name="content" rows="9"
                                  class="form-control ckeditor"
                                  placeholder="Enter page content..">{{ old('content') }}</textarea>
                        @if($errors->has('content'))
                            <span class="help-block animation-slideDown">{{ $errors->first('content') }}</span>
                        @endif
                    </div>
                </div>

                @include('admin.pages.page.page_sections')

                <div class="form-group">
                    <label class="col-md-3 control-label">Is Active?</label>

                    <div class="col-md-9">
                        <label class="switch switch-primary">
                            <input type="checkbox" id="is_active" name="is_active"
                                   value="1" checked>
                            <span></span>
                        </label>
                    </div>
                </div>
                <div class="form-group form-actions">
                    <div class="col-md-9 col-md-offset-3">
                        <a href="{{ route('admin.pages.index') }}" class="btn btn-sm btn-warning">Cancel</a>
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-floppy-o"></i> Save
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            @include('admin.pages.page.meta_fields')
        </div>
        {{ Form::close() }}
    </div>
@endsection

@push('extrascripts')
    <script type="text/javascript" src="{{ asset('public/js/ckeditor/ckeditor.js') }}"></script>
    <script type="text/javascript" src="{{ asset('public/js/libraries/pages.js') }}"></script>
@endpush

resources/views/admin/pages/page/edit.blade.php
@extends('admin.layouts.base')

@section('content')
    <ul class="breadcrumb breadcrumb-top">
        <li><a href="{{ route('admin.pages.index') }}">Pages</a></li>
        <li><span href="javascript:void(0)">Edit Page</span></li>
    </ul>
    <div class="row">
        {{  Form::open([
            'method' => 'PUT',
            'id' => 'edit-page',
            'route' => ['admin.pages.update', $page->id],
            'class' => 'form-horizontal ',
            'files' => TRUE,
            ])
        }}
        <div class="col-md-12">
            <div class="block">
                <div class="block-title">
                    <h2><i class="fa fa-pencil"></i> <strong>Edit Page "{{$page->name}}"</strong></h2>
                </div>
                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="pages_name">Name</label>

                    <div class="col-md-9">
                        <input type="text" class="form-control" id="pages_name" name="name"
                               placeholder="Enter page name.."
                               value="{{  Request::old('name') ? : $page->name }}">
                        @if($errors->has('name'))
                            <span class="help-block animation-slideDown">{{ $errors->first('name') }}</span>
                        @endif
                    </div>
                </div>
                <div class="form-group{{ $errors->has('slug') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="pages_slug">Slug</label>

                    <div class="col-md-9">
                        <input type="text" class="form-control" id="pages_slug" name="slug"
                               placeholder="Enter page slug.."
                               value="{{  Request::old('slug') ? : $page->slug }}">
                        @if($errors->has('slug'))
                            <span class="help-block animation-slideDown">{{ $errors->first('slug') }}</span>
                        @endif
                    </div>
                </div>
                {{--<div class="form-group{{ $errors->has('page_type_id') ? ' has-error' : '' }}">--}}
                    {{--<label class="col-md-3 control-label" for="page_type_id">Type</label>--}}

                    {{--<div class="col-md-9">--}}
                        {{--<select name="page_type_id" id="page_type_id"--}}
                                {{--class="page-type-select"--}}
                                {{--data-placeholder="Choose page type..">--}}
                            {{--<option value=""></option>--}}
                            {{--@foreach($page_types as $page_type)--}}
                                {{--<option value="{{ $page_type->id }}" {{ old('page_type_id') ? : $page->page_type_id == $page_type->id ? 'selected' : '' }}>{{ $page_type->name }}</option>--}}
                            {{--@endforeach--}}
                        {{--</select>--}}
                        {{--@if($errors->has('page_type_id'))--}}
                            {{--<span class="help-block animation-slideDown">{{ $errors->first('page_type_id') }}</span>--}}
                        {{--@endif--}}
                    {{--</div>--}}
                {{--</div>--}}

                {{--<div class="form-group{{ $errors->has('file') ? ' has-error' : '' }}">--}}
                    {{--<label class="col-md-3 control-label" for="file">Banner Image</label>--}}
                    {{--<div class="col-md-9">--}}
                        {{--<div class="input-group">--}}
                            {{--<label class="input-group-btn">--}}
                                {{--<span class="btn btn-primary">--}}
                                    {{--Choose File <input type="file" name="banner_image" style="display: none;">--}}
                                {{--</span>--}}
                            {{--</label>--}}
                            {{--<input type="text" class="form-control" readonly>--}}
                        {{--</div>--}}
                        {{--@if($errors->has('banner_image'))--}}
                            {{--<span class="help-block animation-slideDown">{{ $errors->first('banner_image') }}</span>--}}
                        {{--@endif--}}
                    {{--</div>--}}
                {{--</div>--}}
                {{--<div class="form-group">--}}
                    {{--<label class="col-md-3 control-label" for="banner_image">--}}{{--Banner Image--}}{{--</label>--}}
                    {{--<div class="col-md-9">--}}
                        {{--<a href="{{ asset($page->banner_image) }}" class="zoom img-thumbnail" style="cursor: default !important;" data-toggle="lightbox-image">--}}
                            {{--<img src="{{ asset($page->banner_image) }}" alt="{{ $page->banner_image }}" class="img-responsive center-block" style="max-width: 100px;">--}}
                        {{--</a>--}}
                    {{--</div>--}}
                {{--</div>--}}

                {{--<div class="form-group{{ $errors->has('banner_description') ? ' has-error' : '' }}">--}}
                    {{--<label class="col-md-3 control-label" for="banner_description">Banner Description</label>--}}

                    {{--<div class="col-md-9">--}}
                        {{--<textarea id="banner_description" name="banner_description" rows="9"--}}
                                  {{--class="form-control ckeditor"--}}
                                  {{--placeholder="Enter page banner description..">{!! Request::old('banner_description') ? : $page->banner_description !!}</textarea>--}}
                        {{--@if($errors->has('banner_description'))--}}
                            {{--<span class="help-block animation-slideDown">{{ $errors->first('banner_description') }}</span>--}}
                        {{--@endif--}}
                    {{--</div>--}}
                {{--</div>--}}
                {{--<div class="form-group{{ $errors->has('content') ? ' has-error' : '' }}">--}}
                    {{--<label class="col-md-3 control-label" for="page_content">Content</label>--}}

                    {{--<div class="col-md-9">--}}
                            {{--<textarea id="page_content" name="content" rows="9"--}}
                                  {{--class="form-control ckeditor"--}}
                                  {{--placeholder="Enter page content..">{!! Request::old('content') ? : $page->content !!}</textarea>--}}
                        {{--@if($errors->has('content'))--}}
                            {{--<span class="help-block animation-slideDown">{{ $errors->first('content') }}</span>--}}
                        {{--@endif--}}
                    {{--</div>--}}
                {{--</div>--}}

                @include('admin.pages.page.page_sections')

                <div class="form-group">
                    <label class="col-md-3 control-label">Is Active?</label>

                    <div class="col-md-9">
                        <label class="switch switch-primary">
                            <input type="checkbox" id="is_active" name="is_active"
                                   value="1" {{ Request::old('is_active') ? : ($page->is_active ? 'checked' : '') }}>
                            <span></span>
                        </label>
                    </div>
                </div>
                <div class="form-group form-actions">
                    <div class="col-md-9 col-md-offset-3">
                        <a href="{{ route('admin.pages.index') }}" class="btn btn-sm btn-warning">Cancel</a>
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-floppy-o"></i> Save
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            @include('admin.pages.page.meta_fields')
        </div>
        {{ Form::close() }}
    </div>
@endsection

@push('extrascripts')
    @if ($page->page_sections->contains('type', 'file'))
        <script>
            var oPageSections = {!! $page->page_sections->where('type', 'file') !!}
        </script>
    @endif
    <script type="text/javascript" src="{{ asset('public/js/ckeditor/ckeditor.js') }}"></script>
    <script type="text/javascript" src="{{ asset('public/js/libraries/pages.js') }}"></script>
@endpush

resources/views/admin/pages/page/index.blade.php
@extends('admin.layouts.base')

@section('content')
    @if (auth()->user()->can('Create Page'))
        <div class="row text-center">
            <div class="col-sm-12 col-lg-12">
                <a href="{{ route('admin.pages.create') }}" class="widget widget-hover-effect2">
                    <div class="widget-extra themed-background">
                        <h4 class="widget-content-light"><strong>Add New</strong> Page</h4>
                    </div>
                    <div class="widget-extra-full"><span class="h2 text-primary animation-expandOpen"><i
                                    class="fa fa-plus"></i></span></div>
                </a>
            </div>
        </div>
    @endif
    <div class="block full">
        <div class="block-title">
            <h2><i class="fa fa-archive sidebar-nav-icon"></i>&nbsp;<strong>Pages</strong></h2>
        </div>
        <div class="alert alert-info alert-dismissable page-empty {{$pages->count() == 0 ? '' : 'johnCena' }}">
            <i class="fa fa-info-circle"></i> No pages found.
        </div>
        <div class="table-responsive {{$pages->count() == 0 ? 'johnCena' : '' }}">
            <table id="pages-table"
                   class="table table-bordered table-striped table-vcenter">
                <thead>
                <tr role="row">
                    <th class="text-center">
                        ID
                    </th>
                    <th class="text-left">
                        Name
                    </th>
                    <th class="text-left">
                        Slug
                    </th>
                    {{--<th class="text-left">--}}
                        {{--Type--}}
                    {{--</th>--}}
                    <th class="text-center">
                        Action
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach($pages as $page)
                    <tr data-page-template-id="{{$page->id}}">
                        <td class="text-center">{{ $page->id }}</td>
                        <td class="text-left">{{ $page->name }}</td>
                        <td class="text-left"><a href="{{ url($page->slug) }}" target="_blank">{{ url($page->slug) }}</a></td>
                        {{--<td class="text-left">{{ $page->page_type->name }}</td>--}}
                        <td class="text-center">
                            <div class="btn-group btn-group-xs">
                                @if (auth()->user()->can('Update Page'))
                                    <a href="{{ route('admin.pages.edit', $page->id) }}"
                                       data-toggle="tooltip"
                                       title=""
                                       class="btn btn-default"
                                       data-original-title="Edit"><i class="fa fa-pencil"></i></a>
                                @endif
                                @if (auth()->user()->can('Delete Page'))
                                    <a href="javascript:void(0)" data-toggle="tooltip"
                                       title=""
                                       class="btn btn-xs btn-danger delete-page-btn"
                                       data-original-title="Delete"
                                       data-page-id="{{ $page->id }}"
                                       data-page-route="{{ route('admin.pages.delete', $page->id) }}">
                                        <i class="fa fa-times"></i>
                                    </a>
                                @endif
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

@push('extrascripts')
    <script type="text/javascript" src="{{ asset('public/js/libraries/pages.js') }}"></script>
@endpush